### ISSUE TITLE
Chromecast integration

### ISSUE THREAD

**Issue by yaoyisheng264** [muxinc/chromecast-mux#3]
Hi,

My solution applies the Chromecast V2 receiver SDK and includes private player solution. How can I integration my receiver solution with MUX?

Cheers,
Sam

**Comment by jsanford8** [comment]
Hi @yaoyisheng264 - a new integration for that will need to be built: we have instructions on doing that here: https://docs.mux.com/docs/javascript-building-a-custom-integration.
